@MiAPIMinima_HostAddress = http://localhost:5156

###
GET {{MiAPIMinima_HostAddress}}/api/beers/
Accept: application/json

###
GET {{MiAPIMinima_HostAddress}}/api/beers/1
Accept: application/json

###
POST {{MiAPIMinima_HostAddress}}/api/beers
Content-Type: application/json

{
    "name" : "Pilsen",
    "brewery" : "Backus",
    "type" : "Cerveza artesanal",
    "alcoholContent" : 5.5
}