// <auto-generated />
using System;
using Estudiantes.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Estudiantes.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Estudiantes.Domain.Estudiantes.Estudiante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_estudiantes");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_estudiantes_usuario_id");

                    b.ToTable("estudiantes", (string)null);
                });

            modelBuilder.Entity("Estudiantes.Domain.Matriculas.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uuid")
                        .HasColumnName("curso_id");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("docente_id");

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("estudiante_id");

                    b.Property<DateTime>("FechaMatricula")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_matricula");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_matriculas");

                    b.HasIndex("EstudianteId")
                        .HasDatabaseName("ix_matriculas_estudiante_id");

                    b.ToTable("matriculas", (string)null);
                });

            modelBuilder.Entity("Estudiantes.Domain.Matriculas.Matricula", b =>
                {
                    b.HasOne("Estudiantes.Domain.Estudiantes.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matriculas_estudiantes_estudiante_id");

                    b.Navigation("Estudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
